from fastapi import APIRouter

from app.api.v1 import achievements, admin, auth, blocks, certificates, club_analytics, club_announcements, club_assistant, club_events, club_posts, clubs, contact, dashboard, follows, messages, notifications, opportunities, portfolio, posts, reports, schools, search, subscription, users

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(posts.router)
api_router.include_router(portfolio.router)
api_router.include_router(achievements.router)
api_router.include_router(certificates.router)
api_router.include_router(follows.router)
api_router.include_router(clubs.router)
api_router.include_router(club_events.router)
api_router.include_router(club_posts.router)
api_router.include_router(club_announcements.router)
api_router.include_router(club_analytics.router)
api_router.include_router(club_assistant.router)
api_router.include_router(messages.router)
api_router.include_router(opportunities.router)
api_router.include_router(search.router)
api_router.include_router(schools.router)
api_router.include_router(reports.router)
api_router.include_router(contact.router)
api_router.include_router(blocks.router)
api_router.include_router(notifications.router)
api_router.include_router(dashboard.router)
api_router.include_router(subscription.router)
api_router.include_router(admin.router)
api_router.include_router(admin.uploads_router)
